### ISSUE TITLE
Ember install not getting latest commit...

### ISSUE THREAD

**Issue by javaprog8432** [zakmac/ember-cli-filter-component#10]
I would like to use this, but it is not getting the latest commits when I install this using 'ember install'. I am getting an error, but this commit: https://github.com/zakmac/ember-cli-filter-component/commit/0fdce4eaeee69aec24b35001766b3ebef2d50c87, fixes the issue. I don't want to modify the node_module directly for future breaking purposes.

**Comment by zakmac** [comment]
Hi @javaprog8432, the latest commit is part of an unpublished change set that is intended for a future release.

**Comment by ioleo** [comment]
@zakmac can you publish a minor release with this change?

**Comment by zakmac** [comment]
@loostro I will try and get a minor update out this week to resolve the issue.

**Comment by zakmac** [comment]
The npm distribution has been updated to include the removal of `Ember.EnumerableUtils`. Version has been bumped to v2.0.2.

**Comment by ioleo** [comment]
@zakmac thanks a lot :)
