### ISSUE TITLE
setFilterTimer method fails in IE 10/11

### ISSUE THREAD

**Issue by zakmac** [zakmac/ember-cli-filter-component#14]
Error in console: `setFilterTimerTypeError: Object doesn't support property or method 'parseInt'`

References:
- [Offending code](https://github.com/zakmac/ember-cli-filter-component/blob/feature/addon/components/filter-content/component.js#L128)
- [MDN Number object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#Browser_compatibility)
- [MDN Number.parseInt method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt#Browser_compatibility)

**Note:** other versions of IE may be affected.

**Comment by thebeachdev** [comment]
Lol, I was about to do this. I actually just learned a ton from you doing it though. I didn't know what you where suppose to do with the issue. I forked the code, and was about to implement the fix.

**Comment by zakmac** [comment]
Hey James, this is just to document the bug. You're welcome to create a PR with your fix for evaluation.
