### ISSUE TITLE
Ember.EnumerableUtils has been removed in 2.0.0?

### ISSUE THREAD

**Issue by kscherling** [zakmac/ember-cli-filter-component#7]
Running into the some errors in a new ember project and it looks like this might be the cause...  Any plans to update in the near future?

**Comment by zakmac** [comment]
@kscherling are you able to provide any more information? My main concern is whether you're seeing deprecation warnings or outright errors.

There should be a new version which resolves: #5 and some Ember v2.0.0 deprecation errors; in the near future. If your issue is unrelated to existing bugs I will work a fix into the next release.

**Comment by kscherling** [comment]
@zakmac Thanks for the quick response!

I am running 
**ember: 2.0.0**
**cli: 1.13.8**

And when binding to a basic model, I get the error:
`Uncaught TypeError: Cannot read property 'filter' of undefined`

originating from:
`filteredItems = Ember['default'].EnumerableUtils.filter(this.get('contentComputed'), function(item) {...}`

Following the threads I landed here and amidst the sweet ascii artwork, looks like we're beyond deprication land in 2.0.
https://github.com/emberjs/ember.js/pull/11455

Thoughts?  Thanks again!

**Comment by zakmac** [comment]
This is very helpful, thanks @kscherling. This seems like a bug so I will pick it up into the next release.

**Comment by kscherling** [comment]
Thanks a ton!

**Comment by jgadbois** [comment]
I'm getting the same error - do you have an ETA on the next version?

**Comment by jgadbois** [comment]
Here's a pull that fixes it for me

https://github.com/zakmac/ember-cli-filter-component/pull/8

**Comment by zakmac** [comment]
Closed with merge of #8. Thanks for the fix, @jgadbois .

**Comment by ioleo** [comment]
@zakmac when is v2.1 release planned?
